version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    paths:
      - third_party$
      - builtin$
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
